### ISSUE TITLE
Review del desafío

### ISSUE THREAD

**Issue by tobiasfacello** [JaeLadu/dwf-desafio-m5#1]
Buenas Jae, felicidades por haber llegado al desafío final del módulo.
Tengo una cosa para comentarte, por la cual creo personalmente que tu desafío necesita ajustes...

Cuando entras a jugar y arranca el contador de 3 segundos, cuando uno elige la jugada en ese tiempo termina resultando todo correctamente (respecto a la partida y al cálculo de resultados).

Ahora bien, cuando ninguna de las jugadas se elige, lo que pasa es lo siguiente:
**1-** **Si no elegiste ninguna jugada desde que entraste por primera vez** a la web app, la computadora elige una jugada y sin importar que no hayas jugado... **resultas perdedor** de esa partida.
**2-** **Si ya habias jugado una (o más) partidas desde que entraste por primera vez**, pero por alguna razón no elegiste una jugada en la partida actual... **Toma la jugada de la partida anterior** e igualmente se juega la partida (obviando que después calcula los resultados y define si sos perdedor o ganador).

A lo que voy con todo esto es lo siguiente, sea el caso que sea estamos llegando a la conclusión que únicamente se da cuando el contador termina y pasa a las páginas siguientes (partida y resultados). Por ende, para solventar ese error deberías de encontrar la forma de que cuando el contador llega a 0 no se siga la jugada, sino que avise que el contador terminó para el jugador y que la partida se repite nuevamente (Para no caer en los errores antes mencionados).

Sin más para agregar espero haber sido totalmente claro, no es algo sumamente complejo más allá de todo lo que ya has entregado que por lo que veo... en general el funcionamiento es el indicado, como te decía solo vi ese drama con el contador.

Mucho éxito con la corrección y espero que puedas terminar el desafío sin mayor complejidad. Mucho éxito Jae!

**Comment by JaeLadu** [comment]
Hola Tobi, todo bien? Primero que nada, gracias por tomarte el tiempo de hacer un testeo a fondo, siempre es útil el feedback. Con respecto a lo que me mensionas, lo de no elegír ninguna jugada y perder fué a propósito, el desafío no aclaraba que hacer en este caso y fuí por la opción que me pareció más simple.
Lo que mencionás de que al no elegír nada después de haber jugado una o más partidas antes y que el sistema tome la jugada anterior si es un error, ya le agrego un paso que limpie todo lo que quedó de la jugada anterior así deja de pasar.
De nuevo muchas gracias!

**Comment by tobiasfacello** [comment]
Hola Jae, me alegro que haya sido útil el feedback!
Chequeé el Figma del desafío final del módulo 5 y claramente como bien decís no se menciona el comportamiento que debería de tener al finalizar el contador, así que gracias por corroborar eso ya que sirve mucho para definir a detalle cada comportamiento según la situación dada 🚀 Respecto a lo demás me alegro que lo hayas logrado corregir! Gracias a vos también nuevamente por estar al pendiente e informarnos sobre lo anteriormente mencionado. Mucho éxito de cara al próximo módulo 💪🏼
